Repository stayintarkov/SIT.Manager.Avalonia, pull requests merged in 2024-03, with the labels that each got.

#55 Temporary backendUrl fix for SIT 1.9
  SIT.Manager.Avalonia/ViewModels/PlayPageViewModel.cs
Labels: bug

#102 Fix Opening SIT Config
  SIT.Manager.Avalonia/ViewModels/ToolsPageViewModel.cs
Labels: bug-fix

#101 handle 0 ip
  SIT.Manager.Avalonia/Services/AkiServerService.cs
Labels: bug-fix

#111 Add new readme
  README.md
  images/manager-sc.png
Labels: documentation

#113 Add new log generator button
  SIT.Manager.Avalonia/App.axaml.cs
  SIT.Manager.Avalonia/Interfaces/IDiagnosticService.cs
  SIT.Manager.Avalonia/Localization/en-US.axaml
  SIT.Manager.Avalonia/Localization/ru-RU.axaml
  SIT.Manager.Avalonia/Localization/uk-UA.axaml
  SIT.Manager.Avalonia/Localization/zh-CN.axaml
  SIT.Manager.Avalonia/Localization/zh-HK.axaml
  SIT.Manager.Avalonia/Localization/zh-TW.axaml
  SIT.Manager.Avalonia/Models/DiagnosticsOptions.cs
  SIT.Manager.Avalonia/Services/DiagnosticService.cs
  SIT.Manager.Avalonia/ViewModels/Dialogs/SelectLogsDialogViewModel.cs
  SIT.Manager.Avalonia/ViewModels/ToolsPageViewModel.cs
  SIT.Manager.Avalonia/Views/Dialogs/SelectLogsDialog.axaml
  SIT.Manager.Avalonia/Views/Dialogs/SelectLogsDialog.axaml.cs
  SIT.Manager.Avalonia/Views/ToolsPage.axaml
Labels: enhancement

#121 Fix deadlock
  SIT.Manager.Avalonia/ManagedProcess/ManagedProcess.cs
Labels: bug-fix
